# Generated by Django 2.2.5 on 2019-11-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20191128_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='author_description',
        ),
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='createtime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
